// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmMmc4BEDNTlogRkPj0LsganeEDDxqBP8',
    appId: '1:497899011174:web:673b5613a7ad66d87981a7',
    messagingSenderId: '497899011174',
    projectId: 'amit-fbdee',
    authDomain: 'amit-fbdee.firebaseapp.com',
    databaseURL: 'https://amit-fbdee-default-rtdb.firebaseio.com',
    storageBucket: 'amit-fbdee.appspot.com',
    measurementId: 'G-1S3JS2DJPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnq-_LHHz4PI2Kzbub4Q-ru1Y_3ZJAjk',
    appId: '1:497899011174:android:171ff2c4f27ec7df7981a7',
    messagingSenderId: '497899011174',
    projectId: 'amit-fbdee',
    databaseURL: 'https://amit-fbdee-default-rtdb.firebaseio.com',
    storageBucket: 'amit-fbdee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ic4Za0MSromRa-EHXoU2sC8Ay0R_gG0',
    appId: '1:497899011174:ios:6e13bd12e2aec9d07981a7',
    messagingSenderId: '497899011174',
    projectId: 'amit-fbdee',
    databaseURL: 'https://amit-fbdee-default-rtdb.firebaseio.com',
    storageBucket: 'amit-fbdee.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ic4Za0MSromRa-EHXoU2sC8Ay0R_gG0',
    appId: '1:497899011174:ios:35b42d00d73943847981a7',
    messagingSenderId: '497899011174',
    projectId: 'amit-fbdee',
    databaseURL: 'https://amit-fbdee-default-rtdb.firebaseio.com',
    storageBucket: 'amit-fbdee.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
